# Configuration Jekyll
title: "WeightSHift - Coaching Acceptation de Soi"
description: "Coach en acceptation de soi et alimentation intuitive"
baseurl: ""
url: ""

# IMPORTANT : Inclure le dossier admin
include:
  - admin

# Collections
collections:
  testimonials:
    output: false

# Plugins
plugins:
  - jekyll-sitemap

# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
