site_name: WeightSHift - Coaching Acceptation de Soi
coach_name: Cécile
description: Coach en acceptation de soi et alimentation intuitive. J'aide les
  femmes à sortir des régimes et à s'aimer comme elles sont.
email: contact@coaching-cecile.com
instagram: https://instagram.com/@weightshift
facebook: ""
tiktok: ""
